src/main/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('search.urls')),
]

src/search/urls.py
from django.urls import path, include
from . import views

app_name = "search"
urlpatterns = [
    path('', views.home, name=('home')),
    path('search/', views.search, name=('search')),
]

src/search/models.py
from django.db import models

# Create your models here.

src/search/views.py
from django.shortcuts import render
from datetime import datetime
from elasticsearch import Elasticsearch
import os
module_dir = os.path.dirname(__file__)  # get current directory
file_path = os.path.join(module_dir, 'data.txt')
# Create your views here.
def home(request):
    def load_data():
        f = open(file_path, "r")
        res = es.bulk(body=f.read())
        print(res)
        
    res=None
    es = Elasticsearch(['https://elastic:g2gCWtHCripDhBDaSDb1laqB@example.es.westus2.azure.elastic-cloud.com:9243/'])
    # res = es.get(index="test-index", id=1)
    # print(res['_source'])
    # es.indices.refresh(index="test")
    res = es.search(index="test", body={"query": {"match_all": {}}})
    hits=[hit for hit in res['hits']['hits']]
    n_hits=res['hits']['total']['value']
    return render(request, 'search/home.html',{"n_hits":n_hits,"hits":hits})


def search(request): 
    def get_or_post(param):
        if request.GET.get(param):
            return request.GET.get(param)
        elif request.POST.get(param):
            return request.POST.get(param)
        else:
            return None
    query_string=get_or_post("query_string") 
    print("query_string", query_string)       
    es = Elasticsearch(['https://elastic:g2gCWtHCripDhBDaSDb1laqB@example.es.westus2.azure.elastic-cloud.com:9243/'])
    res = es.search(index="test", q=query_string)
        
    hits=[hit for hit in res['hits']['hits']]
    n_hits=res['hits']['total']['value']
    return render(request, 'search/home.html',{"n_hits":n_hits,"hits":hits, "query_string":query_string})

src/main/templates/base.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>

<head>
    {% load static %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Rastreator</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <!-- <link rel="stylesheet" href="{% static 'css/styles.css'%}"> -->


</head>

<body>

    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.bundle.min.js"></script>
    <script src="https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.js"></script>
    <script src="https://kit.fontawesome.com/cb8588d293.js" crossorigin="anonymous"></script>
    <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
    {% include 'header.html' %}
    <div class="container">{% block content %}{% endblock %} </div>

    <script>
        var x = document.querySelectorAll('input,select,textarea');
        for (var i = 0; i < x.length; i++) {
            if (x[i].type === "file") {
                x[i].classList.add("form-control-file");
            } else if (x[i].type === "checkbox") {} else {
                x[i].classList.add("form-control");
            }
        }
    </script>
</body>

</html>

src/main/templates/header.html
<nav class="navbar navbar-expand-lg navbar-light bg-light shadow  mb-4">
    <div class="container">
        <ul class="navbar-nav">
            <li class="rounded  {% if 'agendas' in request.path %}bg-secondary{% endif %} ">
                <a class="navbar-brand mx-3" href="{% url 'search:home' %}">Rastreator</a>
            </li>
        </ul>
        <form class="form-inline my-2 my-lg-0 col-lg-auto col-md-10 col-sm-9 col-12 px-2" action="{% url 'search:search' %}">
            <input class="form-control col-lg-auto col-md-10 col-sm-9 col-12 mr-2" type="search" name="query_string" placeholder="Buscar" aria-label="Buscar">
            <button class="btn bg-white col-sm-auto col-12 my-2 my-sm-0 shadow" type="submit">Buscar</button>
        </form>

    </div>
    </div>
</nav>

src/search/templates/search/home.html
{% extends 'base.html' %} {% block content %} {% if hits %}{% if query_string %}
<p><strong>Query: </strong>" {{query_string}} "</p>{% endif%}
<p>Showing 1-10 out of {{n_hits}} hits</p>
{% for hit in hits %}
<p>{{hit}}</p> {% endfor %} {% endif %} {% endblock content %}